### ISSUE TITLE
###  Revised 4-Day Plan

### ISSUE THREAD

**Issue by ZohalMirkhel** [ZohalMirkhel/space-travelers#1]
### **Day 1: September 1, 2024**
- **GitHub Repository Setup**: Create a new repository on GitHub, configure settings, initialize with a README, and set up necessary branches. [0.2H]
- **Project Initialization**: Install Node.js and set up the initial project structure. [1H]
- **Setting up Redux store if Possible**

### **Day 2: September 2, 2024**
- **Redux Store Setup**: Finalize setting up the Redux store, including creating `actions`, `reducers`, and `store` files. [2-3H]
- **Routing Setup**: Set up React Router for navigation, ensuring basic routes are configured. [2H]
- **Start Working on Individual Tasks if Possible**

### **Day 3: September 3, 2024**
- **Individual Pages Setup**: Complete setup of individual pages (Rockets Page and Missions Page). [4-6H]
- **Profile Page Setup**: Begin setting up the Profile Page to display reserved rockets and joined missions. [3-4H]
- **Start Working on Design if Possible**

### **Day 4: September 4, 2024**
- **Website Design**: Continue and finalize the design of the website, ensuring responsiveness and visual appeal. [3-5H]
- **Finalization**: Complete final tasks including:
  - Code Review
  - Final Testing
  - Deployment Preparation
  - Project Submission [1H]

**Comment by ahzamir** [comment]
@ZohalMirkhel 
@WALWALASAFI 

- Well done, great daily plan prepared by your team

**Comment by ahzamir** [comment]
- Please have a look at my comments on all of your issues and implement them you don't need to request a re-review on your Kanban board just implement the feedback and start working on your project
