### ISSUE TITLE
Redux Store Setup (Group-Task) - [4H]

### ISSUE THREAD

**Issue by ZohalMirkhel** [ZohalMirkhel/space-travelers#4]
- **Task Description**: Set up the basic structure for Redux in the project.

  **Tasks Involved**:
  - **Zohal Mirkhel**:
    - Create the `store.js` file to initialize the Redux store.
    - Create the `reducers.js` file to manage the application state.
  
  - **Walwala Safi**:
    - Create the `actions.js` file to define and export action creators.

**Comment by ahzamir** [comment]
- Remember that creating empty files are okay to divide among yourself but the codes inside each file should be done by both of your for example:

- The Missions page component belongs to Zohal, so Zohal is responsible for adding the actions that have been dispatched on her component and also adding her missions state to the reducer and updating it according to the actions that have been dispatched and getting all data from API inside rect files and at the end add her state inside the redux store, and the other team member is responsible for her part
